name: Bug Report
description: Report a bug or issue
title: "[BUG] <title>"
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Before Reporting...
      description: "Make sure you have done the following:"
      options:
        - label: I have searched the existing issues and can confirm that a similar report has not already been submitted.
          required: true
        - label: I have consulted the [Wiki](https://github.com/Neodymium7/BundleBD/wiki) and [FAQ](https://github.com/Neodymium7/BundleBD/wiki/FAQ) to see if my issue was already addressed.
          required: true
  - type: textarea
    attributes:
      label: Issue Description
      description: A clear and concise description of what you're experiencing and the behavior you expected.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Screenshots? Anything that will give more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
